version: '3.1'
services :

  pavshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: devsearch_backend
    container_name: backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    tty: true
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: devsearch
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    

