# Generated by Django 4.0.5 on 2022-09-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
